### ISSUE TITLE
No module named 'transformers'

### ISSUE THREAD

**Issue by pk3725069** [v-mipeng/LexiconAugmentedNER#13]
File "/Users/ling/Program/LexiconAugmentedNER/model/gazlstm.py", line 8, in <module>
    from transformers.modeling_bert import BertModel
ModuleNotFoundError: No module named 'transformers'
需要安装pip包吗？

**Comment by v-mipeng** [comment]
需要安装transformers包

**Comment by yikedouer** [comment]
> 需要安装transformers包

你好，请问transformers是什么版本，新一点的版本似乎代码结构有变化，按照您代码的导入方式会失败

**Comment by 2hip3ng** [comment]
请问transformers的版本是多少啊？ModuleNotFoundError: No module named 'transformers.modeling_bert'
