### ISSUE TITLE
KeyError: 1

### ISSUE THREAD

**Issue by lqqdeyhm** [v-mipeng/LexiconAugmentedNER#18]
自己构建了一个简单的医疗领域的数据集，想要用已训练好的模型直接进行测试，但是在这份数据上没法正常标注“BME“，总是遇到含有多个matched list中多个值（例如matched_Id [1, 2723] matched_list ['指数', '指']）的情况下出错。
原来给定的数据测试正常。

gazs_count[idx][0].append(gaz_count[matched_Id[w]])
KeyError: 1

**Comment by ccjluff** [comment]
meet the same problem, it seems that the code dose not provide the predict function, we can not predict the new com utterances...

**Comment by gungunXD** [comment]
你好，方便的话可以将你使用的测试集发给我（rtma19@fudan.edu.cn），我看看具体的情况

**Comment by lqqdeyhm** [comment]
> 你好，方便的话可以将你使用的测试集发给我（[rtma19@fudan.edu.cn](mailto:rtma19@fudan.edu.cn)），我看看具体的情况
谢谢，现在已经知道是什么问题了，因为新的数据需要重新构建gaz,word,biword alphabet，重新统计词频，否则就找不到对应的数据。

**Comment by Biaocsu** [comment]
@lqqdeyhm 你好，请问重新构建gaz,word,biword alphabet时有什么需要注意的吗？我重新对预测数据进行构造，结果发现还是报错，望指点避坑

**Comment by waterwaterrr** [comment]
> > 你好，方便的话可以将你使用的测试集发给我（[rtma19@fudan.edu.cn](mailto:rtma19@fudan.edu.cn)），我看看具体的情况
> > 谢谢，现在已经知道是什么问题了，因为新的数据需要重新构建gaz,word,biword alphabet，重新统计词频，否则就找不到对应的数据。

假如我有一份新的测试集，在做训练的时候我是拿不到他的，只有在测试的时候才拿得到，然后用已有的数据构建词频，那我想要预测该怎么做

**Comment by waterwaterrr** [comment]
> > > 你好，方便的话可以将你使用的测试集发给我（[rtma19@fudan.edu.cn](mailto:rtma19@fudan.edu.cn)），我看看具体的情况
> > > 谢谢，现在已经知道是什么问题了，因为新的数据需要重新构建gaz,word,biword alphabet，重新统计词频，否则就找不到对应的数据。
> 
> 假如我有一份新的测试集，在做训练的时候我是拿不到他的，只有在测试的时候才拿得到，然后用已有的数据构建词频，那我想要预测该怎么做

假如在测试的时候重新统计一遍词频，新的词的进入，会导致字典大小的变动，导致跟原本训练时维度不匹配，就会报错
