### ISSUE TITLE
关于如何与预训练模型BERT结合

### ISSUE THREAD

**Issue by yolanda182** [v-mipeng/LexiconAugmentedNER#47]
你好👋打扰一下！请问直接将use_bert设置为True就是结合bert了嘛？（之前跑过Bert相关模型，都需要配置相关文件，所以很疑惑将其改成True就是结合了嘛？）
我将其改为True之后，会碰见报错：Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) 请问您碰到过吗

**Comment by 550952213** [comment]
老哥，你咋解决的
