### ISSUE TITLE
使用了CLUENER2020数据集，为什么验证集的数据很正常，测试集一个都没有预测正确呢？

### ISSUE THREAD

**Issue by piaopu0120** [v-mipeng/LexiconAugmentedNER#48]
![image](https://user-images.githubusercontent.com/47666845/145166589-2ce4e567-01de-46af-93ed-a40371f778ec.png)

**Comment by 550952213** [comment]
老哥，能给个qq么，有些问题想请假

**Comment by piaopu0120** [comment]
> 老哥，能给个qq么，有些问题想请假

我看了你提交的issue，没有数据集的话网上找找能够转换BIO的代码，自己转换就行。

**Comment by 550952213** [comment]
不是，我跑的比你准确率高不少啊

**Comment by 550952213** [comment]
不是转bio的问题，我的指标和你差好多，我想知道为什么

**Comment by 550952213** [comment]
我的CLUENER2020数据量为啥只有这么点gold_num =  1630  pred_num =  1630  right_num =  1529，而且结果太高了
Test: time: 2.87s, speed: 167.47st/s; acc: 0.9666, p: 0.9380, r: 0.9380, f: 0.9380
Best dev score: p:0.9324414715719064, r:0.9311957247828991, f:0.9318181818181818
Test score: p:0.938036809815951, r:0.938036809815951, f:0.938036809815951
