### ISSUE TITLE
求问，有人跑过CLUENER2020，想问问大佬们

### ISSUE THREAD

**Issue by 550952213** [v-mipeng/LexiconAugmentedNER#58]

**Comment by 550952213** [comment]
gold_num =  1630  pred_num =  1616  right_num =  1465
Test: time: 2.93s, speed: 163.86st/s; acc: 0.9523, p: 0.9066, r: 0.8988, f: 0.9026
Best dev score: p:0.8806779661016949, r:0.8677354709418837, f:0.8741588156123822
Test score: p:0.906559405940594, r:0.8987730061349694, f:0.9026494146642021
没跑几轮都上90了F1，但官方最高也才80几，bio、bmes和cluener2020原版jsion格式的数据集都用过，指标都上90.想问问大佬们，哪里出错了
![M7_YO`62X(6NH3Y4AB)V6MI](https://user-images.githubusercontent.com/77155407/162573794-2cafe787-2e27-4755-824f-79c5ce892c51.png)

**Comment by GaoYb923** [comment]
楼主跑的值好高，不明觉厉！
不过CLUE2020官方提供的数据集中，测试集是没有标注的，所以这个f1值有没有可能有问题呢？
我之前跑过几个epoch，没跑完100个。暂时大概是79点几
榜单上的结果不知道是不是测试集上的
请问楼主读过文献上的结果吗，求分享~

**Comment by 550952213** [comment]
暂时没看到文献有，但我dev数据集指标也好高，为啥啊，榜单上的要提交给网站评测好像。后来我把训练和dev数据集合起来，再8.2.2分割，指标也上90，是我哪里出问题了吗。您是把地址直接改成cluener数据集的地址吗，代码其他地方有需要改的么。外文基本没人用cluener的感觉，核心也少。后来我换数据集了，这数据集感觉好麻烦啊

**Comment by 550952213** [comment]
> 楼主跑的值好高，不明觉厉！ 不过CLUE2020官方提供的数据集中，测试集是没有标注的，所以这个f1值有没有可能有问题呢？ 我之前跑过几个epoch，没跑完100个。暂时大概是79点几 榜单上的结果不知道是不是测试集上的 请问楼主读过文献上的结果吗，求分享~

**Comment by 550952213** [comment]
> 楼主跑的值好高，不明觉厉！ 不过CLUE2020官方提供的数据集中，测试集是没有标注的，所以这个f1值有没有可能有问题呢？ 我之前跑过几个epoch，没跑完100个。暂时大概是79点几 榜单上的结果不知道是不是测试集上的 请问楼主读过文献上的结果吗，求分享~

**Comment by GaoYb923** [comment]
我是直接使用clue2020官方的数据集，不使用测试集，想跑一下看看效果。
代码，参数都没改
Best dev score: p:0.7916801031925186, r:0.7991536458333334, f:0.79539931961769
Test score: p:0.0, r:-1, f:-1
我认为您重新调整分割，改变了数据集的分布，使其和原始数据集不再一致了，实验结果有变动应该是正常的，您试试输出cnoll格式结果对比看看呢。
您的方法可行啊，在这组数据集上和其他方法对比的时候，都使用您分割的数据集跑，看看效果。

**Comment by 550952213** [comment]
已解决

**Comment by 550952213** [comment]
模型，code里输入default地址没用，会导致结果都一样

**Comment by 550952213** [comment]
msra也没dev，看作者答复说是取dev结果当作结果（好像看过作者的回复）。榜单上的需要提交代码给网站
